### ISSUE TITLE
guardar puntos de referencia en navegador para no preguntarlos cada vez

### ISSUE THREAD

**Issue by mpericay** [geomatico/the-perfect-spot#15]

**Comment by martitasea** [comment]
Esta tarea solo pretende guardar en localStorage la info de los puntos (añadir y borrar)
`{
  'blue': [
    	{'lat': 12, 'lon': 2, 'name': 5},
     {'lat': 12, 'lon': 2, 'name': 5}
  ],
  'red': [
    {'lat': 12, 'lon': 2, 'name': 5},
     {'lat': 12, 'lon': 2, 'name': 5}
  ]
}`
